version: "3"
services:
  mysql:
    image: mysql
    volumes:
       - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
volumes:
  db-data:
